COMPONENT = SourceBroadcasterAppC

CFLAGS += $(SLP_PARAMETER_CFLAGS)

CFLAGS += -I"../common/routing/gossip"

include ../common/tinyos/makefile.common

#include $(TINYOS_ROOT_DIR)/Makefile.include
include $(MAKERULES)
