#ifndef SLPDUTYCYCLEFLAGS_H
#define SLPDUTYCYCLEFLAGS_H

enum
{
    SLP_DUTY_CYCLE_IS_NEW = (1 << 0),
    SLP_DUTY_CYCLE_IS_FIRST_FAKE = (1 << 1),
    SLP_DUTY_CYCLE_IS_ADJACENT_TO_FAKE = (1 << 2),
    SLP_DUTY_CYCLE_VALID_TIMESTAMP = (1 << 3),
};

#endif // SLPDUTYCYCLEFLAGS_H
