COMPONENT = SourceBroadcasterAppC

CFLAGS += -Wnonnull -Wpointer-arith -Wshadow

CFLAGS += $(SLP_PARAMETER_CFLAGS) -DTOSH_DATA_LENGTH=32

#include $(TINYOS_ROOT_DIR)/Makefile.include
include $(MAKERULES)
