COMPONENT = ../adaptive_spr_notify/SourceBroadcasterAppC

CFLAGS += -I"../adaptive_spr_notify"
CFLAGS += -I"../adaptive_spr_notify/lpl"
CFLAGS += $(SLP_PARAMETER_CFLAGS)

include ../common/makefile.common

#include $(TINYOS_ROOT_DIR)/Makefile.include
include $(MAKERULES)
