COMPONENT = SourceBroadcasterAppC

CFLAGS += -Wnonnull -Wpointer-arith -Wshadow -Wformat

CFLAGS += $(SLP_PARAMETER_CFLAGS)

CFLAGS += -I"../common"

#include $(TINYOS_ROOT_DIR)/Makefile.include
include $(MAKERULES)
