#ifndef SLP_SPANNING_TREE_H
#define SLP_SPANNING_TREE_H

enum {
	AM_SPANNING_TREE_SETUP = 15,
	AM_SPANNING_TREE_CONNECT = 16,
};

#define SLP_MAX_1_HOP_NEIGHBOURHOOD 10

#endif // SLP_SPANNING_TREE_H
