#ifndef SLP_CONSTANTS_H
#define SLP_CONSTANTS_H

#define MESSAGE_QUEUE_SIZE 15

enum Channels
{
	NORMAL_CHANNEL = 1,
    DISSEM_CHANNEL = 2,
    SEARCH_CHANNEL = 3,
    LOOP_CHANNEL = 4
};

#define SLP_MAX_NUM_SOURCES 1

#endif // SLP_CONSTANTS_H
