#ifndef SLP_CONSTANTS_H
#define SLP_CONSTANTS_H

enum Channels
{
	NORMAL_CHANNEL = 1,
	CHOOSE_CHANNEL = 2,
	FAKE_CHANNEL = 3,
};

#define SLP_MAX_NUM_SOURCES 16
#define SLP_MAX_NUM_SINKS 1

#endif // SLP_CONSTANTS_H
