COMPONENT = ../phantom/SourceBroadcasterAppC

CFLAGS += -I"../phantom"
CFLAGS += $(SLP_PARAMETER_CFLAGS)

include ../common/makefile.common

#include $(TINYOS_ROOT_DIR)/Makefile.include
include $(MAKERULES)
