#ifndef SLP_CONSTANTS_H
#define SLP_CONSTANTS_H

#define MESSAGE_QUEUE_SIZE 15

enum Channel
{
	NORMAL_CHANNEL = 1,
    EMPTYNORMAL_CHANNEL = 2
};

#define SLP_MAX_NUM_SOURCES 1
#define SLP_MAX_NUM_SINKS 1

#endif // SLP_CONSTANTS_H
