#ifndef SLP_CONSTANTS_H
#define SLP_CONSTANTS_H

enum Channels
{
	NORMAL_CHANNEL = 1,
	AWAY_CHANNEL = 2,
	CHOOSE_CHANNEL = 3,
	FAKE_CHANNEL = 4
};

#define AWAY_DELAY_MS (SOURCE_PERIOD_MS / 2)

#endif // SLP_CONSTANTS_H
