#ifndef SLP_CONSTANTS_H
#define SLP_CONSTANTS_H

#define MESSAGE_QUEUE_SIZE 15

enum Channels
{
	NORMAL_CHANNEL = 1,
    BEACON_CHANNEL = 2,
    DISSEM_CHANNEL = 3,
};

#define SLP_MAX_NUM_SOURCES 1

#endif // SLP_CONSTANTS_H
