
CFLAGS += -Wall -Wextra -Wnonnull -Wpointer-arith -Wshadow -Wformat  -Wfloat-equal -Wno-unused-parameter -Wno-unused-variable


ifdef USE_SERIAL_PRINTF

CFLAGS += -I$(TOSDIR)/lib/printf -DNEW_PRINTF_SEMANTICS

CFLAGS += -Wsign-compare -Wpointer-sign

else

CFLAGS += -Werror=pointer-sign -Werror=format

endif
